package com.blazartech.MultiDroolsDemo.comp.process.drools;

import com.blazartech.MultiDroolsDemo.comp.data.CompensationRecord;
import com.blazartech.MultiDroolsDemo.comp.data.EventAllocation;
import com.blazartech.MultiDroolsDemo.comp.data.Product;
import com.blazartech.MultiDroolsDemo.comp.data.CompensationProgram;
import com.blazartech.MultiDroolsDemo.comp.data.ThresholdType;
import java.math.BigDecimal;

// calculate the compensation on all created allocations
rule 'calculate compensation'
when
    compensationRecord: CompensationRecord(getAmount() == null, getCompensationRate() > 0)
then
    compensationRecord.setAmount(compensationRecord.getEventAllocation().getCompensableEvent().getAmount().multiply(BigDecimal.valueOf(compensationRecord.getCompensationRate())));
    update(compensationRecord);
end