package com.blazartech.MultiDroolsDemo.comp.process.drools;

dialect 'mvel';
dialect 'java';

import com.blazartech.MultiDroolsDemo.comp.data.CompensationRecord;
import com.blazartech.MultiDroolsDemo.comp.data.EventAllocation;
import com.blazartech.MultiDroolsDemo.comp.data.Product;
import com.blazartech.MultiDroolsDemo.comp.data.CompensationProgram;
import com.blazartech.MultiDroolsDemo.comp.data.ThresholdType;

// calculate the compensation on all created allocations
rule 'calculate compensation'
when
    compensationRecord: CompensationRecord(amount == null, compensationRate > 0)
then
    compensationRecord.amount = compensationRecord.eventAllocation.compensableEvent.amount * compensationRecord.compensationRate;
    update(compensationRecord);
end