package com.blazartech.MultiDroolsDemo.comp.process.drools;

import com.blazartech.MultiDroolsDemo.comp.data.CompensationRecord;
import com.blazartech.MultiDroolsDemo.comp.data.EventAllocation;
import com.blazartech.MultiDroolsDemo.comp.data.Product;
import com.blazartech.MultiDroolsDemo.comp.data.CompensationProgram;
import com.blazartech.MultiDroolsDemo.comp.data.ThresholdType;

// determine if a transaction is eligible to calc
rule 'Determine isPayable'
when
    $eventAllocation: EventAllocation(getProgram() != null)
then
    $eventAllocation.setEligibleToCalc(true);
    update($eventAllocation);
end

