
package com.blazartech.MultiDroolsDemo.comp.process.drools;

dialect 'mvel';
dialect 'java';

import com.blazartech.MultiDroolsDemo.comp.data.CompensableEvent;
import com.blazartech.MultiDroolsDemo.comp.data.CompensationRecord;
import com.blazartech.MultiDroolsDemo.comp.data.EventAllocation;
import com.blazartech.MultiDroolsDemo.comp.data.Product;
import com.blazartech.MultiDroolsDemo.comp.data.CompensationProgram;
import com.blazartech.MultiDroolsDemo.comp.data.ThresholdType;

// create event allocations for a compensable event
rule 'create event allocations'
when
    compensableEvent: CompensableEvent()
then
    EventAllocation eventAllocation = new EventAllocation();
    eventAllocation.setCompensableEvent(compensableEvent);
    eventAllocation.setAgentNumber("DBS001");
    eventAllocation.setId(compensableEvent.getId() * 10);
    eventAllocation.setProgram(CompensationProgram.FYC);

    EventAllocation eventAllocation2 = new EventAllocation();
    eventAllocation2.setCompensableEvent(compensableEvent);
    eventAllocation2.setAgentNumber("DBS001");
    eventAllocation2.setId(eventAllocation.getId() + 1);
    eventAllocation2.setProgram(CompensationProgram.RenewalCommission);

    insert(eventAllocation);
    insert(eventAllocation2);
end